spring:
  datasource:
    url: ${DB_URL}
    password: ${DB_PASSWORD}
    username: ${DB_USER}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true